php:
  version: '7.3'
  timezone: 'America/New_York'
node:
  version: '12.14.1'
  npm:
    global: [eslint, gulp, bower, eslint-config-google, eslint-config-standard, eslint-config-airbnb, eslint-config-standard, eslint-plugin-jsx-a11y, eslint-plugin-react, eslint-plugin-import]

apt:
  repos:
    - name: Papirus icon theme
      repo: 'ppa:papirus/papirus'
    - name: Numix theme
      repo: 'ppa:numix/ppa'
    - name: Google Chrome
      repo: 'deb http://dl.google.com/linux/chrome/deb/ stable main'
    - name: Yarn
      repo: 'deb https://dl.yarnpkg.com/debian/ stable main'
      gpg: 'https://dl.yarnpkg.com/debian/pubkey.gpg'
    - name: Sublime Text & Merge
      repo: 'deb https://download.sublimetext.com/ apt/stable/'
      gpg: 'https://download.sublimetext.com/sublimehq-pub.gpg'
  packages:
    install:
      list:
        - curl
        - default-jdk
        - default-jre
        - dia
        - evolution
        - evolution-ews
        - exfat-fuse
        - exfat-utils
        - google-chrome-stable
        - mc
        - nfs-common
        - numix-blue-gtk-theme
        - numix-gtk-theme
        - numix-icon-theme
        - numix-icon-theme-circle
        - sublime-merge
        - sublime-text
        - telegram-desktop
        - transmission
        - vlc
        - zsh
      deb:
        - https://download.xnview.com/XnViewMP-linux-x64.deb
        - https://downloads.slack-edge.com/linux_releases/slack-desktop-4.2.0-amd64.deb
        - https://go.skype.com/skypeforlinux-64.deb
        - https://zoom.us/client/latest/zoom_amd64.deb
    offline:
      download:
        - ansible
        - linux-image-5.3.0-26-generic
        - linux-modules-5.3.0-26-generic
        - linux-modules-extra-5.3.0-26-generic
        - linux-headers-5.3.0-26-generic
        - build-essential
        - exfat-fuse
        - exfat-utils
        - net-tools
      filters:
        - grep -v "^ "
        - grep -v "^kldutils$"
        - grep -v "^libc-dev$"
        - grep -v "^debconf-"
        - grep -v "^python3-cffi-backend-api-"
        - grep -v "^perlapi-"
        - grep -v "^perl-openssl-abi-"
drivers:
  - name: RTL8812AU
    repo: https://github.com/gordboy/rtl8812au-5.6.4.2
  - name: RTL8822BU
    repo: https://github.com/EntropicEffect/rtl8822bu
